### ISSUE TITLE
Feature: More internal links

### ISSUE THREAD

**Issue by PerWiklander** [UNECE/GSIM-2.0#8]
It would help navigating the spec if there were more internal links in the dokument.

An example:

3.2.5 Classification Index

A Classification Index shows the relationship between text found in statistical data sources (responses to survey questionnaires, administrative records) and one or more [Statistical Classifications](https://unece.github.io/GSIM-2.0/GSIMv2.html#statistical-classification). A Classification Index may be used to assign the codes for [Classification Items](https://unece.github.io/GSIM-2.0/GSIMv2.html#classification-item) to observations in acquisitions of statistical data. A [Statistical Classification](https://unece.github.io/GSIM-2.0/GSIMv2.html#statistical-classification) is a subtype of [Node Set](https://unece.github.io/GSIM-2.0/GSIMv2.html#node-set). The relationship between [Statistical Classification](https://unece.github.io/GSIM-2.0/GSIMv2.html#statistical-classification) and Classification Index can also be extended to include the other Node Set types - [Code List](https://unece.github.io/GSIM-2.0/GSIMv2.html#code-list) and [Category Set](https://unece.github.io/GSIM-2.0/GSIMv2.html#category-set). A Classification Index can relate to one particular or to several [Statistical Classifications](https://unece.github.io/GSIM-2.0/GSIMv2.html#statistical-classification).

**Comment by Chris-ECE** [comment]
Yes, noted. - That's a good suggestion, but I think this might be a long-term aspiration, as we may need to make some future decisions about how to structure/store the glossary content. (For example, we might want to explore storing the data separately, and pulling it into the webpage rather than storing it as html within the page.)

The sidebar is a partial solution for navigation (but maybe not as convenient as the individual links that you suggest).

**Comment by PerWiklander** [comment]
+1 on this "we might want to explore storing the data separately, and pulling it into the webpage rather than storing it as html within the page".

But I understand that it is not a simple task.
